version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: nosql-la-crime-mongo
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["--auth"]

  mongo-express:
    image: mongo-express
    container_name: nosql-la-crime-mexpress
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: nosql-la-crime-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret

  backend:
    build: .
    container_name: nosql-la-crime-api
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    ports:
      - "8000:8000"